server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javeduser?characterEncoding=UTF-8
    username: renyanyu
    password: Hk7Ne&1;5j
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

